apiVersion: apps/v1
kind: Deployment
metadata:
  name: twiddit-ldap
spec:
  replicas: 1
  selector:
    matchLabels:
      role: twiddit-ldap
  template:
    metadata:
      labels:
        role: twiddit-ldap
    spec:
      containers:
        - args:
            - --copy-service
          env:
            - name: COMPOSE_HTTP_TIMEOUT
              value: "200"
            - name: LDAP_ADMIN_PASSWORD
              value: admin
            - name: LDAP_BACKEND
              value: hdb
            - name: LDAP_BASE_DN
            - name: LDAP_CONFIG_PASSWORD
              value: config
            - name: LDAP_DOMAIN
              value: twiddit.unal.edu.co
            - name: LDAP_LOG_LEVEL
              value: "256"
            - name: LDAP_ORGANISATION
              value: Twiddit
            - name: LDAP_READONLY_USER
              value: "false"
            - name: LDAP_REMOVE_CONFIG_AFTER_SETUP
              value: "true"
            - name: LDAP_REPLICATION
              value: "false"
            - name: LDAP_SSL_HELPER_PREFIX
              value: ldap
            - name: LDAP_TLS
              value: "true"
            - name: LDAP_TLS_CA_CRT_FILENAME
              value: ca.crt
            - name: LDAP_TLS_CIPHER_SUITE
              value: SECURE256:-VERS-SSL3.0
            - name: LDAP_TLS_CRT_FILENAME
              value: ldap.crt
            - name: LDAP_TLS_ENFORCE
              value: "false"
            - name: LDAP_TLS_KEY_FILENAME
              value: ldap.key
            - name: LDAP_TLS_PROTOCOL_MIN
              value: "3.1"
            - name: LDAP_TLS_VERIFY_CLIENT
              value: demand
          image: osixia/openldap:1.1.8
          name: twiddit-ldap
          ports:
            - containerPort: 389
            - containerPort: 636
          resources: {}
          stdin: true
          tty: true
          volumeMounts:
            - mountPath: /var/lib/ldap
              name: twiddit-ldap-claim0
            - mountPath: /etc/ldap/slapd.d
              name: twiddit-ldap-claim1
            - mountPath: /container/service/slapd/assets/certs/
              name: twiddit-ldap-claim2
            - mountPath: ./bootstrap.ldif:/container/service/slapd/assets/config/bootstrap/ldif/50-bootstrap.ldif
              name: twiddit-ldap-claim3
      hostname: twiddit-unal-edu-co
      restartPolicy: Always
      volumes:
        - name: twiddit-ldap-claim0
          persistentVolumeClaim:
            claimName: twiddit-ldap-claim0
        - name: twiddit-ldap-claim1
          persistentVolumeClaim:
            claimName: twiddit-ldap-claim1
        - name: twiddit-ldap-claim2
          persistentVolumeClaim:
            claimName: twiddit-ldap-claim2