apiVersion: apps/v1
kind: Deployment
metadata:
  name: twiddit-search-service
spec:
  selector:
    matchLabels:
      app: twiddit-search-service
  replicas: 1
  template:
    metadata:
      labels: 
        app: twiddit-search-service
    spec:
      containers:
        - name: twiddit-search-service
          image: gcr.io/inlaid-booth-388620/search-engine-ms@sha256:ededc2d1963e576c418cd1d4987e4082c98daf267a40c4fee36a54b2aa042dec
          ports:
            - containerPort: 22100
---
apiVersion: v1
kind: Service
metadata:
  name: twiddit-search-service
spec:
  selector:
    app: twiddit-search-service
  ports:
  - protocol: TCP
    port: 22100
    targetPort: 22100
status:
  loadBalancer: {}