apiVersion: apps/v1
kind: Deployment
metadata:
  name: twiddit-communiddits
spec:
  selector:
    matchLabels:
      app: twiddit-communiddits
  replicas: 1
  template:
    metadata:
      labels: 
        app: twiddit-communiddits
    spec:
      containers:
        - name: twiddit-communiddits
          image: gcr.io/inlaid-booth-388620/communiddits-ms
          ports:
            - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: twiddit-communiddits
spec:
  selector:
    app: twiddit-communiddits
  ports:
  - protocol: TCP
    port: 3001
    targetPort: 3001
  type: LoadBalancer
status:
  loadBalancer: {}