apiVersion: apps/v1
kind: Deployment
metadata:
  name: twiddits-ms
spec:
  selector:
    matchLabels:
      app: twiddits-ms
  replicas: 1
  template:
    metadata:
      labels: 
        app: twiddits-ms
    spec:
      containers:
        - name: twiddits-ms
          image: gcr.io/inlaid-booth-388620/twiddits-ms
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: twiddits-ms
spec:
  selector:
    app: twiddits-ms
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: LoadBalancer
status:
  loadBalancer: {}