#ldap 
apiVersion: v1
kind: PersistentVolumeClaim 
metadata:
  name: twiddit-ldap-claim0
spec:
  accessModes:
    - ReadOnlyMany 
  resources:
    requests:
      storage: 100Mi

---

apiVersion: v1
kind: PersistentVolumeClaim 
metadata:
  name: twiddit-ldap-claim1
spec:
  accessModes:
    - ReadOnlyMany 
  resources:
    requests:
      storage: 100Mi

---

apiVersion: v1
kind: PersistentVolumeClaim 
metadata:
  name: twiddit-ldap-claim2
spec:
  accessModes:
    - ReadOnlyMany 
  resources:
    requests:
      storage: 100Mi


--- 

apiVersion: v1
kind: PersistentVolumeClaim 
metadata:
  name: twiddit-ldap-claim3
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
status: {}

---

# RabbitMQ
apiVersion: v1
kind: PersistentVolumeClaim 
metadata:
  name: rabbitmq-claim0
spec:
  accessModes:
    - ReadOnlyMany 
  resources:
    requests:
      storage: 100Mi

---

# RabbitMQ
apiVersion: v1
kind: PersistentVolumeClaim 
metadata:
  name: rabbitmq-claim1
spec:
  accessModes:
    - ReadOnlyMany 
  resources:
    requests:
      storage: 100Mi



