# ldap
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: twiddit-ldap-claim0
spec:
  storageClassName: standard-rwo
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: twiddit-ldap-claim1
spec:
  storageClassName: standard-rwo
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi


---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: twiddit-ldap-claim2
spec:
  storageClassName: standard-rwo
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: twiddit-ldap-claim3
  name: twiddit-ldap-claim3
spec:
  storageClassName: standard-rwo
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
status: {}


