apiVersion: apps/v1
kind: Deployment
metadata:
  name: twiddit-wa
spec:
  selector:
    matchLabels:
      app: twiddit-wa
  replicas: 1
  template:
    metadata:
      labels: 
        app: twiddit-wa
    spec:
      containers:
        - name: twiddit-wa
          image: gcr.io/inlaid-booth-388620/twiddit-wa
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: twiddit-wa
spec:
  selector:
    app: twiddit-wa
  ports:
  - protocol: TCP
    port: 82
    targetPort: 80
  type: LoadBalancer
status:
  loadBalancer: {}