apiVersion: apps/v1
kind: Deployment
metadata:
  name: twiddit-profile
spec:
  selector:
    matchLabels:
      app: twiddit-profile
  replicas: 1
  template:
    metadata:
      labels: 
        app: twiddit-profile
    spec:
      containers:
        - name: twiddit-profile
          env:
            - name: DB_HOST
              value: 34.73.157.104
            - name: DB_USER
              value: ccordero
            - name: DB_PASSWORD
              value: twiddit
            - name: DB_NAME
              value: users
          image: gcr.io/inlaid-booth-388620/profile-ms
          ports:
            - containerPort: 7777
---
apiVersion: v1
kind: Service
metadata:
  name: twiddit-profile
spec:
  selector:
    app: twiddit-profile
  ports:
  - protocol: TCP
    port: 7777
    targetPort: 7777
  type: LoadBalancer
status:
  loadBalancer: {}