apiVersion: apps/v1
kind: Deployment
metadata:
  name: twiddit-profile
spec:
  selector:
    matchLabels:
      app: twiddit-profile
  replicas: 1
  template:
    metadata:
      labels: 
        app: twiddit-profile
    spec:
      containers:
        - name: twiddit-profile
          env:
            - name: DB_HOST
              value: 10.66.16.3
            - name: DB_USER
              value: profile-ms
            - name: DB_PASSWORD
              value: NuevoPass
            - name: DB_NAME
              value: users
            - name: RABBITMQ_IP
              value: http://rabbitmq
          image: gcr.io/inlaid-booth-388620/profile-ms
          ports:
            - containerPort: 7777
---
apiVersion: v1
kind: Service
metadata:
  name: twiddit-profile
spec:
  selector:
    app: twiddit-profile
  ports:
  - protocol: TCP
    port: 7777
    targetPort: 7777
  type: LoadBalancer
status:
  loadBalancer: {}