apiVersion: v1
kind: Service
metadata:
  name: twiddit-profile
spec:
  selector:
    app: twiddits-profile
  ports:
  - protocol: TCP
    port: 7777
    targetPort: 7777
  type: LoadBalancer
status:
  loadBalancer: {}