apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-ms
spec:
  selector:
    matchLabels:
      app: auth-ms
  replicas: 1
  template:
    metadata:
      labels: 
        app: auth-ms
    spec:
      containers:
        - name: auth-ms
          env: 
            - name: SECRET
              value: 1414
            - name: PORT
              value: 394eeec66de5e0b6cc46540ce65f4e8f
          image: gcr.io/inlaid-booth-388620/auth-ms
          ports:
            - containerPort: 1414