apiVersion: v1
kind: Service
metadata:
  name: auth-ms
spec:
  selector:
    app: auth-ms
  ports:
  - protocol: TCP
    port: 1414
    targetPort: 1414
  # type: LoadBalancer
status:
  loadBalancer: {}